# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-02 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20161102_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_obj', to='contenttypes.ContentType'),
        ),
    ]
