# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-02 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('actions', '0003_auto_20161102_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='object_id',
            new_name='target_id',
        ),
        migrations.RemoveField(
            model_name='action',
            name='content_type',
        ),
        migrations.AddField(
            model_name='action',
            name='target_ct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_obj', to='contenttypes.ContentType'),
        ),
    ]
