# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-10-21 05:45
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='users/default.png', upload_to=accounts.models.upload_path_handler),
        ),
    ]
