# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(upload_to='users/%Y/%m/%d'),
        ),
    ]
