# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161108_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contack',
            options={'ordering': ('-created',)},
        ),
    ]
