# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:49
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160929_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(upload_to=accounts.models.upload_path_handler),
        ),
    ]
