# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160929_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='users/default.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
