# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-30 02:53
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160929_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='users/default.png', upload_to=accounts.models.upload_path_handler),
        ),
    ]
