# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-01 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='settings',
        ),
    ]
