# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-02 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20161102_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='collector', to='blog.Post'),
        ),
    ]
