# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-23 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [],
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='blog_tags', to='blog.Tag'),
        ),
    ]
