# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='id1',
        ),
    ]
