# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161015_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id1',
            new_name='id',
        ),
    ]
